package com.demo.openai.controller;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.Map;
import java.util.Objects;

/**
 * REST controller for handling AI chat operations with OpenAI.
 * <p>
 * This controller provides HTTP endpoints for interacting with the OpenAI ChatClient.
 * It accepts user prompts and returns responses generated by the AI model.
 * All endpoints are configured with GET mappings and return JSON responses.
 * </p>
 *
 * @author Pramod Rajane
 * @version 1.0
 * @since 2026-06-14
 */
@org.springframework.web.bind.annotation.RestController
public class RestController {

    /**
     * The ChatClient instance used for communicating with OpenAI models.
     * <p>
     * This client is injected via constructor dependency injection and is used
     * to send prompts and receive responses from the AI.
     * </p>
     */
    private final ChatClient chatClient;

    /**
     * Constructs a new RestController with the specified ChatClient.
     * <p>
     * This constructor uses Spring's constructor injection to provide the ChatClient
     * dependency. The ChatClient is configured automatically by Spring Boot's
     * auto-configuration mechanism.
     * </p>
     *
     * @param chatClient the ChatClient instance to be used for AI interactions,
     *                   must not be null
     */
    public RestController(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    /**
     * Processes a user prompt and returns both the prompt and AI-generated response.
     * <p>
     * This method handles GET requests to {@code /get/{prompt}} and sends the provided
     * prompt to the OpenAI ChatClient. It returns a Map containing the original prompt
     * and the corresponding response from the AI model.
     * </p>
     *
     * @param prompt the user's input prompt to be sent to the AI model.
     *               Extracted from the request path variable. Must not be null or empty.
     * @return a Map containing:
     *         <ul>
     *           <li>{@code "prompt"}: the original user prompt</li>
     *           <li>{@code "response"}: the AI-generated response from OpenAI</li>
     *         </ul>
     * @throws NullPointerException if the AI model response is null
     */
    @GetMapping("/get/{prompt}")
    public Map<String, String> getPromptResponse(@PathVariable String prompt) {
        try {
            return Map.of(
                    "prompt", prompt,
                    "response", Objects.requireNonNull(chatClient.prompt()
                            .user(prompt)
                            .call()
                            .content())
            );
        } catch (Exception e) {
            // Log the exception (you can use a logging framework like SLF4J)
            System.err.println("Error processing prompt: " + e.getMessage());
            // Return an error response
            return Map.of(
                    "prompt", prompt,
                    "response", "Error processing prompt: " + e.getMessage()
            );
        }

    }
}
